<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9e150127-9a64-4cb2-89ac-aff20ef22769</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Frontend\Frontend.csproj" />
    <ProjectReference Include="..\Backend.ApiService\Backend.ApiService.csproj" />
    <ProjectReference Include="..\Backend.Web\Backend.Web.csproj" />
  </ItemGroup>

</Project>
