<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6b9224d8-70b9-4c90-8a43-816c9314c82b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frontend.ApiService\Frontend.ApiService.csproj" />
    <ProjectReference Include="..\Frontend.Web\Frontend.Web.csproj" />
  </ItemGroup>

</Project>
